
          [build]
            command = 'yarn tinabuild'
            functions = 'functions'
            publish = 'public'

          [[redirects]]
                  from = "/our-team"
                  to = "/testing-new-fake-url"
                
[[redirects]]
                  from = "/test-1"
                  to = "/test-2"
                
        